# Generated by Django 5.2 on 2025-05-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(default='Пустое поле', max_length=40, verbose_name='Название станка')),
                ('machine_type', models.CharField(default='Пустое поле', max_length=100, verbose_name='Тип станка')),
                ('status', models.CharField(default='Пустое поле', max_length=20, verbose_name='Статус')),
                ('full_text', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
