# Generated by Django 5.2 on 2025-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Станок', 'verbose_name_plural': 'Станки'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='m_name',
            field=models.CharField(max_length=40, verbose_name='Название станка'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(max_length=100, verbose_name='Тип станка'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
    ]
