# Generated by Django 5.2 on 2025-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_options_alter_machine_m_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='working_hours_per_day',
            field=models.FloatField(default=8.0, verbose_name='Часы работы в день'),
        ),
    ]
