# Generated by Django 5.2 on 2025-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_working_hours_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('свободен', 'Свободен'), ('занят', 'Занят')], max_length=20),
        ),
    ]
