# Generated by Django 5.2 on 2025-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AddField(
            model_name='schedule',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание'), ('in_progress', 'В работе'), ('done', 'Готово')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(verbose_name='Плановое окончание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(verbose_name='Плановое начало'),
        ),
    ]
