# Generated by Django 5.2 on 2025-05-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0003_machine_working_hours_per_day'),
        ('orders', '0003_alter_order_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Завершено')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Станок')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderdetail', verbose_name='Деталь в заявке')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
                'ordering': ['start_time'],
            },
        ),
    ]
