# Generated by Django 5.2 on 2025-05-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='schedule',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое окончание'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическое начало'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('in_progress', 'В работе'), ('done', 'Готово')], default='waiting', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(verbose_name='Планируемое окончание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(verbose_name='Планируемое начало'),
        ),
    ]
