# Generated by Django 5.2 on 2025-05-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_is_complete_schedule_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='setup_time',
            field=models.IntegerField(default=0, verbose_name='Подготовительное время (мин)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='unit_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер единицы'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='unit_time',
            field=models.IntegerField(default=0, verbose_name='Штучное время (мин)'),
        ),
    ]
