# Generated by Django 5.2 on 2025-05-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_alter_machine_status'),
        ('orders', '0007_alter_order_deadline'),
        ('schedule', '0003_schedule_setup_time_schedule_unit_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'План работы', 'verbose_name_plural': 'Планы работы'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='setup_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='unit_number',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='unit_time',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderdetail'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
    ]
