# Generated by Django 5.2 on 2025-05-09 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 5, 16, 17, 7, 31, 648718, tzinfo=datetime.timezone.utc), verbose_name='Дедлайн'),
        ),
    ]
