# Generated by Django 5.2 on 2025-05-08 11:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_working_hours_per_day'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='detail',
            name='machines',
            field=models.ManyToManyField(to='machines.machine', verbose_name='Подходящие станки'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='Неизвестный клиент', max_length=100, verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 5, 15, 11, 47, 31, 668560, tzinfo=datetime.timezone.utc), verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_process', 'В работе'), ('done', 'Завершено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='detail',
            name='height',
            field=models.FloatField(verbose_name='Высота (мм)'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='length',
            field=models.FloatField(verbose_name='Длина (мм)'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер детали'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='piece_time',
            field=models.IntegerField(verbose_name='Время штучное (мин)'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='prep_time',
            field=models.IntegerField(verbose_name='Время подготовительное (мин)'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='width',
            field=models.FloatField(verbose_name='Ширина (мм)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='Наименование прибора'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.detail'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
