# Generated by Django 5.2 on 2025-05-08 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_detail_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 5, 15, 12, 11, 24, 646339, tzinfo=datetime.timezone.utc), verbose_name='Дедлайн'),
        ),
    ]
