# Generated by Django 5.2 on 2025-05-11 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 5, 18, 11, 20, 11, 420696, tzinfo=datetime.timezone.utc), verbose_name='Дедлайн'),
        ),
    ]
