# Generated by Django 5.2 on 2025-05-11 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2025, 5, 18, 13, 41, 51, 944943, tzinfo=datetime.timezone.utc), verbose_name='Дедлайн'),
        ),
    ]
